apiVersion: ramendr.openshift.io/v1alpha1
kind: Recipe
metadata:
  name: PLACEHOLDER
spec:
  appType: busybox
  groups:
  - backupRef: PLACEHOLDER
    excludedResourceTypes:
    - events
    - event.events.k8s.io
    - persistentvolumes
    - replicaset
    - persistentvolumeclaims
    - pods
    includedNamespaces:
    - PLACEHOLDER
    labelSelector:
      matchExpressions:
      - key: appname
        operator: In
        values:
        - busybox_app1-1
        - busybox_app1-2
        - busybox_app1-3
        - busybox_app1-4
        - busybox_app1-5
        - busybox_app1-6
        - busybox_app1-7
        - busybox_app1-8
        - busybox_app1-9
        - busybox_app1_10
    name: PLACEHOLDER
    type: resource
  workflows:
  - failOn: any-error
    name: backup
    sequence:
    - hook: deployment-check/stateReady
    - group: PLACEHOLDER
  - failOn: any-error
    name: restore
    sequence:
    - group: PLACEHOLDER
    - hook: deployment-check/stateReady
  hooks:
  - name: deployment-check
    type: check
    namespace: PLACEHOLDER
    selectResource: deployment
    nameSelector: "busybox-*"
    timeout: 800
    onError: fail
    chks:
    - name: stateReady
      timeout: 900
      onError: fail
      condition: "{$.spec.replicas} == {$.status.readyReplicas}"
  volumes:
    includedNamespaces:
    - PLACEHOLDER
    name: mypvc
    type: volume
    labelSelector:
      matchExpressions:
      - key: appname
        operator: In
        values:
        - busybox_app1-1
        - busybox_app1-2
        - busybox_app1-3
        - busybox_app1-4
        - busybox_app1-5
        - busybox_app1-6
        - busybox_app1-7
        - busybox_app1-8
        - busybox_app1-9
        - busybox_app1_10
